# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'adpieSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for adpieSwift
    pod 'AdPieSDK', '~> 1.2'
    pod 'SnapKit', '~> 5.0.0'
end


post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end